### ISSUE TITLE
Broken link to the ARC group's repo with suggested config files for autoformatting/linting

### ISSUE THREAD

**Issue by lbokeria** [alan-turing-institute/REG-handbook#100]
## Description

On the [Python Tools and Practices](https://alan-turing-institute.github.io/REG-handbook/docs/technical_practices/python/) page, in the [Autoformatting/linting section](https://alan-turing-institute.github.io/REG-handbook/docs/technical_practices/python/#autoformatters--linters), the link to ARC group's repo with suggested configuration files is broken. 

## Expected behaviour

It should likely just point to the parent directory: https://github.com/alan-turing-institute/ARC/tree/master/code-style/

## Actual behaviour

It currently points to: https://github.com/alan-turing-institute/ARC/tree/master/code-style/suggested-config which does not exist

**Comment by lbokeria** [comment]
Actually, maybe it shouldn't link to the parent directory. It should directly link to a file that suggests pre-commit hook configuration.

The parent [Code style](https://github.com/alan-turing-institute/ARC/tree/master/code-style/) folder in the ARC repo also contains broken links to the [suggested-config](https://github.com/alan-turing-institute/ARC/blob/master/code-style/suggested-config) file which does not exist. 

@jack89roberts does this suggested-config file exist somewhere in a new location? Tagging you cause I see you made the last commit to the repo.

**Comment by jack89roberts** [comment]
Ah right I've been slowly updating(/breaking) things in the ARC repo/wiki. I think I deleted those as they're in the new ARC project template repo now: https://github.com/alan-turing-institute/ARC-project-template
