### ISSUE TITLE
Build pages failing with latest version of Hugo

### ISSUE THREAD

**Issue by dsj976** [alan-turing-institute/REG-handbook#149]
## Description

With the latest version of Hugo (`v0.126`), the `hugo --minify` command in the `pre-commit` checks fails with the following error:

```
no such template "_internal/google_analytics_async.html". 
```

This seems to be because this template has been deprecated (see discussion [here](https://discourse.gohugo.io/t/build-error-on-v0-125-2-calling-internal-template-internal-google-analytics-async-html/49410)). I was able to run Hugo locally by replacing "_internal/google_analytics_async.html" with "_internal/google_analytics.html" in the `themes/book` submodule of the REG Handbook repo. However, on GitHub the book theme is pinned directly to `v9` of  the [hugo-book repo](https://github.com/alex-shpak/hugo-book), which is the latest release and hasn't been updated since 2021.

## Expected behaviour

The pages should be built successfully with the latest version of Hugo (`v0.126`)

## How to reproduce

Run `hugo server --minify` with the latest version of Hugo

---

**Comment by dsj976** [comment]
@JimMadge any thoughts on how to solve this easily?

**Comment by JimMadge** [comment]
Fork the theme? Migrate to a maintained theme?
