### ISSUE TITLE
Updates to recruitment FAQs

### ISSUE THREAD

**Issue by penelopeysm** [alan-turing-institute/REG-handbook#154]
Feel free to edit to add other things

- [x] How to request reasonable adjustments
- [x] New mailing list

**Comment by Cyara-she-her** [comment]
Apologies for missing something here; I'm unclear if I should be following up with a specific action or simply thinking about this for our next meeting? (Coincidentally I'll be away this coming Tues so will miss the next meeting)

**Comment by KatrionaGoldmann** [comment]
We could also add a section with other resources which REG have been involved in. Perhaps a 'where can I hear more?' section? with links to: 
- [ ] [code for thought podcast](https://codeforthought.buzzsprout.com/1326658/14761258-en-building-data-science-teams-alan-turing-institute-skills-and-policy-award-part-i)
- [ ] [Data science and AI careers: a spotlight series](https://www.turing.ac.uk/data-science-and-ai-careers-spotlight-series?utm_source=LinkedIn&utm_medium=Text_link&utm_campaign=Turing-Spotlight-on-data-science-and-AI-careers)
- [ ] [REG spotlight series](https://www.turing.ac.uk/work-turing/research/research-engineering-group#researcher-spotlight)
- [ ] Turing podcast episodes - some of these are already linked in the profile section.

**Comment by penelopeysm** [comment]
Here's an older video with Sarah G: https://www.youtube.com/watch?v=WIYaXzXLLY4
