### ISSUE TITLE
Add summary of reasonable adjustment policy

### ISSUE THREAD

**Issue by penelopeysm** [alan-turing-institute/REG-handbook#159]
It's here: https://thealanturininstitute.sharepoint.com/sites/gc/Public%20Documents/Corporate%20Governance/Policies/People%20Policies/Reasonable%20Adjustment%20Policy%20Final.pdf

It's relevant both for current staff and also prospective applicants.

**Comment by KatrionaGoldmann** [comment]
Existing public facing version of the policy can be found here: https://www.turing.ac.uk/reasonable-adjustments-policy
