### ISSUE TITLE
Add 'unspoken expectations' to handbook

### ISSUE THREAD

**Issue by KatrionaGoldmann** [alan-turing-institute/REG-handbook#166]
Document the unspoken expectations in how we work. e.g. :
- it is ok to eat in meetings
- it is ok to have your camera off
- we don’t operate 9-5
- dress code?
- what does flexible working mean? 
  - you can be full time in office
  - you can request a permanent desk in the office

**Comment by llewelld** [comment]
Such a great idea!

**Comment by KatrionaGoldmann** [comment]
This has been merged into the [faqs_update](https://github.com/alan-turing-institute/REG-handbook/tree/faqs_update) branch. Closing here with further developments in #154.
