### ISSUE TITLE
Link checking CI between pages in different chapters does not work

### ISSUE THREAD

**Issue by andrewphilipsmith** [alan-turing-institute/REG-handbook#40]
## Description
Link checking CI between pages in different chapters does not work.

## Expected behaviour
When linking to a page in a different chapter, I would expect to enter in the form:
```
[other interesting page](../../other_chapter/other_page)
```
Note that there are two parent directory `..` in the path.

In a local instance of hugo, this works correctly. The path in the browser is:
localhost:1313/REG-handbook/docs/our_projects/project_outputs/
Note that this includes the `docs` directory.

## Actual behaviour
This is interpreted differently by the CI and results in an error. eg:

https://github.com/alan-turing-institute/REG-handbook/runs/6919002296?check_suite_focus=true#step:4:150

```
FILE: ./content/docs/how_we_work/code_audits.md
[✖] ../../our_projects/project_outputs → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/content/our_projects/project_outputs'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/github/workspace/content/our_projects/project_outputs'
}
```
Note that the `docs` dir is missing from the path.

## How to reproduce

1. Create a new branch.
2. Create a page with a relative link to a page in a different chapter.
3. Adjust the link so that it works correctly using a local hugo instance.
4. Commit your change and create a pull request.
5. Check the CI output.

**Comment by JimMadge** [comment]
I _think_ links in HTML cannot be relative. Hugo provides short codes for this which also ensure that the link is valid at build time:

https://gohugo.io/content-management/cross-references/
