### ISSUE TITLE
Add content on SocRSE and how to claim back subs

### ISSUE THREAD

**Issue by DavidBeavan** [alan-turing-institute/REG-handbook#52]
## Problem
Add detail on REG members being encouraged to join [Society of Research Software Engineering](https://society-rse.org/) and that REG will reimburse professional subscriptions to individuals.

## Solution

* Expand [existing content](https://github.com/alan-turing-institute/REG-handbook/blob/2ac17111fe831945e416dbefb244bf4c2066aeb9/content/docs/onboarding/new_joiners/systems_set_up.md?plain=1#L139) in [Systems Set Up](https://alan-turing-institute.github.io/REG-handbook/docs/onboarding/new_joiners/systems_set_up/):
* Highlight the [benefits of SocRSE](https://society-rse.org/join-us/)
* Say REG supports it
* Tell staff how to claim back subscriptions - Certify, don't select a project, claim quickly after payment

## Alternatives

* Happy to discuss alternative places for this content
---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by llewelld** [comment]
An attempt to add this info in: https://github.com/alan-turing-institute/REG-handbook/pull/64
