### ISSUE TITLE
Some pages use fixed rather than semantic line-lengths

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/REG-handbook#68]
## Description

The [current advice](https://alan-turing-institute.github.io/REG-handbook/docs/contributing/style_guide/#semantic-line-breaks) for contributing to the handbook is that semantic line breaks should be used. The linting rules are set up accordingly.

[Previously](https://github.com/alan-turing-institute/REG-handbook/commit/b176a1f9) a maximum line length of 80 characters was enforced. The result is that several files still conform wholly or partially to the 80 character line limit.

"As a contributor, I'd like all files to conform to the style guide, so that I can add new contributions without it being confusing, and without the resulting file looking inconsistent."

## Expected behaviour

All files have semantic line breaks.

## Actual behaviour

Some files have lines split at 80 characters.

The following files are the ones I could see that appear to have 80-character line lengths:

[contributing/discussions_and_issues.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/contributing/discussions_and_issues.md)
[contributing/reviewing_changes.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/contributing/reviewing_changes.md)
[contributing/getting_started.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/contributing/getting_started.md)
[contributing/creating_a_page.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/contributing/creating_a_page.md)
[contributing/advanced.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/contributing/advanced.md)
[contributing/contributing_changes.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/contributing/contributing_changes.md)
[contributing/editing_a_page.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/contributing/editing_a_page.md)
[contributing/_index.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/contributing/_index.md)
[how_we_work/meeting_record.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/how_we_work/meeting_record.md)
[technical_practices/software_dev_best_practice.md](https://raw.githubusercontent.com/alan-turing-institute/REG-handbook/main/content/docs/technical_practices/software_dev_best_practice.md)

## Screenshots

N/A

## How to reproduce

Select one of the links in the list above.

## Your personal setup

N/A

# Paste relevant logs here
N/A

**Comment by JimMadge** [comment]
😬 You're of course welcome to fix this.

Some thoughts,

- There is currently a mix of semantic line breaks, fixed width, one paragraph per line
- It might not be very fun to fix
- While good code hygiene, it doesn't affect the rendering of the book 🤷 
- I don't know any way to enforce semantic line breaks (it isn't as simple as new line after a period), if there was one, I would be pretty happy with enforcing it
- It is very likely other contributors will ignore the recommendation
