### ISSUE TITLE
Add instructions on doing Markdown linting locally

### ISSUE THREAD

**Issue by yongrenjie** [alan-turing-institute/REG-handbook#69]
## Problem

It's a bit annoying to push and have CI fail because of Markdown linting.

https://alan-turing-institute.github.io/REG-handbook/docs/contributing/contributing_changes/ mentions Markdown linting, but doesn't tell you how to do it locally.

## Solution

Add instructions on installing `mdl` and possibly including a pre-commit hook for Git.

Briefly:

1. `brew install ruby` (don't use system one or else you need sudo to install gems)
2. `export PATH=/opt/homebrew/opt/ruby/bin:${PATH}`
3. `gem install mdl`
4. `gem env | grep 'EXECUTABLE DIRECTORY'` -> get the directory and use it in the next step
5. `export PATH=/opt/homebrew/lib/ruby/gems/3.2.0/bin:${PATH}`
6. `mdl --ignore-front-matter --style .mdl_style.rb ./content` (note the submodule gives a lot of errors so has to be excluded from linting. Alternatively can use -g flag to lint only the files git sees, which excludes submodules, but that causes issue/PR templates to fail. May be easier to just fix the issue/PR templates)

## Alternatives (not recommended)

1. Look at CI fail
7. Deep sigh
8. Remove extra whitespace, `git commit --amend && git push -f`

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by yongrenjie** [comment]
(While we're at it, it'd probably be nice to have a link to the contributing page on the repo readme.)

**Comment by llewelld** [comment]
There is some existing info about `mdl` in the [Style Guide](https://alan-turing-institute.github.io/REG-handbook/docs/contributing/style_guide/#style-enforcement) section, but it's not as comprehensive as the useful info you've provided. Perhaps what you've written could be added there?

Having said that, given that it (I'm guessing) you didn't find this info when looking, perhaps it would be better to also move all of the linting info to the [Contributing Changes](https://alan-turing-institute.github.io/REG-handbook/docs/contributing/contributing_changes/) section?

**Comment by yongrenjie** [comment]
@llewelld Yes, I somehow skipped over that page entirely - thanks for the pointer!

I'm thinking adding the info to the Style Guide page, and then putting a pointer to it from Contributing Changes should be fine? I can do it tomorrow or some time this week.

**Comment by llewelld** [comment]
Nice: that sounds like a good way to do it to me.
