### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/REG-handbook#95]
## Description
The search box doesn't work.

## Expected behaviour

Typing in the search box should produce results instantly under the search box, with links to relevant website pages - see the [hugo-book demo](https://hugo-book-demo.netlify.app/ for an example

## Actual behaviour

Nothing happens when you type in the search box.

It appears the search never finds anything. On the main branch of `hugo-book`, the search seems to work slightly differently from the `v9` release, which our site is based on, in that it seems to generate a search index on first use of the search box. I tried updating the code locally, but it didn't seem to help.

May be related to a reported issue [here](https://github.com/alex-shpak/hugo-book/issues/363), which is marked as closed, in which `flexsearch` ignores the base URL and can't handle search when the site is in a subdirectory. I tried the suggested fixes locally, but they didn't seem to work.

## How to reproduce

Type anything in the search box.

## Your personal setup

- OS: MacOS 12.6.3
- Hugo version: hugo v0.111.1+extended darwin/arm64 
- <details><summary>Logs</summary>

Tested on Chrome and Safari, on desktop and mobile browsers.

**Comment by JimMadge** [comment]
It works locally for me, where `BaseURL` is `http://localhost:1313/REG-handbook/`.

The `BaseURL` in the config, for the production site, looks correct to me.

**Comment by edwardchalstrey1** [comment]
just noticed this also

**Comment by craddm** [comment]
Seems to be working now!

**Comment by JimMadge** [comment]
Fixed itself 😕 . Maybe a Hugo update.
